version: '3'

services:
  rabbit:
    image: rabbitmq:3-management    
    restart: unless-stopped
    environment:
      RABBITMQ_ERLANG_COOKIE: 'SWQOKODSQALRPCLNMEQG'
      RABBITMQ_DEFAULT_USER : 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - '15672:15672'
      - '5672:5672'
    networks:
      - cqenet
      
  mongo:
    image: mongo    
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'hts-test'
      MONGO_INITDB_ROOT_PASSWORD: 'passw0rd'
    ports:
      - '27017:27017'
    networks:
      - cqenet
      
# cqelight:
#   build: .
#   depends_on:
#     - mongo
#     - rabbit
#   networks:
#     - cqenet
    
networks:
  cqenet:
    driver: bridge